### ISSUE TITLE
codegen issues

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#14]
Some issues/ideas for the current `codegen`:
- [x] code(#50): equation in context has intricate dependencies - **low**
 - idea: generate codes for `finds` before generate codes for `contexts`
- [ ] decide: can we do `print(42)` in our language - **low**
- [x] code(#68) only add `#include` statements if it is needed - **low**
- [x] code(#47): move `find` to a separate function 
- [x] code(#48): match the context of `find` with the variables in the context
- [x] code(#43): assigning value for variable more than once declares C var more than one

**Comment by nnhoang** [comment]
should we create separate issues for each of this?

**Comment by jzacsh** [comment]
Just preference I guess. I personally don't think that's necessary, unless someone starts working on one and would like a separate issue to discuss all the details?

**Comment by jzacsh** [comment]
marking this closed, since we have "respectable" codegen now :)
