### ISSUE TITLE
more respectable semantic analysis phase

### ISSUE THREAD

**Issue by jzacsh** [rxie25/PLT2016Spring#24]
For hello world - now that we've averted emergency in #15, and have **something** to work with - we should do some real analysis (eg: the fun "is this an unknown variable"-logic we dreamed up in our LRM)

 *Some* examples of current limitations:
 - [x] **issue  #51**: reject `find ID` when `ID` has never been seen
 - [ ] in progress (#56) reject `find`-blocks that include unresolved `ID`s inside
 - [ ] in progress(#56) - **sast**: detect and mark vars as _"to be resolved [by user]"_
 - [ ] ... more I'm not thinking of right now....?

To start, these both require that we:
1. build a walkable sast of the variable-dependencies per Context
2. Walk both and throw if our tree indicates it
